### PR TITLE
fix: Resolve issues with datetime comparisons in scenarios where microsecond precision is provided in the underlying value.

### LINKED ISSUE #2069: Filtering by Dates with Table Service no longer working in 3.25.0
### Steps to reproduce the issue?

This sample C# code demonstrates the issue, running this in 3.24.0 will output results, in 3.25.0 it returns nothing.

```
_using Microsoft.Azure.Cosmos.Table;

namespace TestTableCreateAndList

{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            // Create a CloudStorageAccount object
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true");

            // Create a CloudTableClient object
            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

            // Get a reference to the table
            CloudTable table = tableClient.GetTableReference("TestTable");

            table.CreateIfNotExists();

            var dataTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

            TestEntity testEntity = new TestEntity { MyDate = dataTime, RowKey= "1", PartitionKey= "2" };

            TableOperation insertOrReplaceOperation = TableOperation.InsertOrReplace(testEntity);

            // Execute the operation
            TableResult result = await table.ExecuteAsync(insertOrReplaceOperation);

            string filter = TableQuery.GenerateFilterConditionForDate("MyDate", QueryComparisons.Equal, dataTime);          
            
            // This does work, using GenerateFilterCondition
            // string filter = TableQuery.GenerateFilterCondition("MyDate", QueryComparisons.Equal, dataTime.ToString());              

            // Create a TableQuery object with the filter
            TableQuery<TestEntity> query = new TableQuery<TestEntity>().Where(filter);

            // Execute the query            
            TableQuerySegment<TestEntity> resultSegment = await table.ExecuteQuerySegmentedAsync(query, null);
            
            // Display the result
            foreach (TestEntity entity in resultSegment.Results)
            {
                Console.WriteLine(entity.RowKey);
            }
        }
    }

    public class TestEntity : TableEntity
    {
        public DateTime MyDate { get; set; }
    }
}_
```

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

In the debug logs we see this.

It seems that the filter has datetime before the filter value: MyDate eq datetime'1970-01-01T00:00:00.0000000Z', it works if filter value: MyDate eq '1970-01-01T00:00:00.0000000Z' when using GenerateFilterCondition

_v24

```
2023-07-25T15:27:47.511Z 59b40689-be99-403c-87e3-b67d6e3f1dfc info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"filter":"MyDate eq datetime'1970-01-01T00:00:00.0000000Z'"},"requestId":"78656609-32d7-4248-8cbf-517dddbd6379","dataServiceVersion":"3.0;"},"version":"2017-07-29"}
2023-07-25T15:27:47.514Z 59b40689-be99-403c-87e3-b67d6e3f1dfc debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[{\"odata.etag\":\"W/\\\"datetime'2023-07-25T15%3A27%3A47.4012873Z'\\\"\",\"PartitionKey\":\"2\",\"RowKey\":\"1\",\"MyDate@odata.type\":\"Edm.DateTime\",\"MyDate\":\"1970-01-01T00:00:00.0000000Z\",\"Timestamp\":\"2023-07-25T15:27:47.4012873Z\"}]}"
```

v25

```
23-07-25T15:34:35.033Z 2d7e6abe-6f10-4eba-a55f-9b401db19ef2 info: HandlerMiddleware: DeserializedParameters={"options":{"queryOptions":{"filter":"MyDate eq datetime'1970-01-01T00:00:00.0000000Z'"},"requestId":"9920f2f4-c6d5-4b18-bc0a-1db351c3486e","dataServiceVersion":"3.0;"},"version":"2017-07-29"}
2023-07-25T15:34:35.036Z 2d7e6abe-6f10-4eba-a55f-9b401db19ef2 debug: TableHandler:queryEntities() Raw response string is "{\"odata.metadata\":\"http://127.0.0.1:10002/devstoreaccount1/$metadata#Tables/@Element\",\"value\":[]}"_
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

### PR DESCRIPTION
**Pull request by notheotherben**
This PR makes some changes to the way our query interpreter is architected, enabling us to handle `DateTime` comparisons with more appropriate custom logic which avoids the `myField eq datetime'2023-07-27T14:01:00.000000Z'` query failing to match backend entries with the same underlying format due to the manner in which JavaScript's `Date` constructor truncates these values.

Fixes #2069

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
Thanks @notheotherben! Add @EmmaZhu and @blueww for checking.

**Review by EmmaZhu — APPROVED** [review]

File: src/table/persistence/QueryInterpreter/QueryNodes/GuidNode.ts [hunk 1]
```diff
@@ -23,11 +22,21 @@ export default class GuidNode<T> implements IQueryNode {
...
 
-  legacyStorageFormat(): string {
-    return this.value;
-  }
+  compare(context: IQueryContext, other: IQueryNode): number {
+    const otherValue = other.evaluate(context);
+    let thisValue = this.value;
+
+    // If the other value is not in its raw GUID format, then let's convert this value to its base64 representation
+    if (!/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}/i.test(otherValue)) {
```
Comment (blueww) [inline src/table/persistence/QueryInterpreter/QueryNodes/GuidNode.ts:30]: if the GUID is with upper case letter A-F, will this check still work?

Comment (notheotherben) [reply src/table/persistence/QueryInterpreter/QueryNodes/GuidNode.ts:30]: It should do - the `/.../i` marks this regex as case-insensitive. Though now that I look at it this is missing the leading and trailing matchers, give me a sec to fix that.

Comment (notheotherben) [reply src/table/persistence/QueryInterpreter/QueryNodes/GuidNode.ts]: Latest version should be a bit more robust (and also rebases on the latest `main` revision to resolve the merge conflict).

**Review by blueww — APPROVED** [review]
