### PR TITLE
Additional checks on table creation

### LINKED ISSUE #1355: Emulator doesn't throw error when creating tables with same name but different casing
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the Azurite was used?
3.15.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
The emulator does not respond with an error when creating a table using an existing name with different casing.

For example, if a table named "table01" exists, I expect an error to be returned by the emulator if I try to create a table named "TABLE01".

According to the [Azure documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names), table names are supposed to be case-insensitive.

### Steps to reproduce the issue?

1. Install and run Azurite.
2. Use the Azure SDK for JavaScript to create a table named "table01":
   ```js
   const client1 = TableClient.fromConnectionString("<DEV CONNECTION STRING>", "table01", { allowInsecureConnection: true });
   await client1.createTable();
   ```
3. Use the Azure SDK for JavaScript to create a table named "TABLE01":
   ```js
   const client2 = TableClient.fromConnectionString("<DEV CONNECTION STRING>", "TABLE01", { allowInsecureConnection: true });
   await client2.createTable();
   ```

### Have you found a mitigation/solution?
No

### LINKED ISSUE #1379: No error when creating a table named "tables"
### Which service (blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
3.14.3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
npm

### What's the Node.js version?
16.13.1

### What problem was encountered?
Azurite does not return an error when attempting to create a table named "tables".

### Steps to reproduce the issue

1. Start Azurite
2. Using @azure/data-tables, create a client object connecting to the local emulator.
3. Use the client to create a table named "tables".

### Have you found a mitigation/solution?
No. Azure proper returns an error response. The [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names) also clearly states that "tables" is a reserved table name.

### PR DESCRIPTION
**Pull request by edwin-huber**
Adds additional tests and checks for table names on creation.
Fixes #1379  
Fixes #1355

### CODE REVIEW

File: src/table/persistence/LokiTableMetadataStore.ts [hunk 1]
```diff
@@ -124,9 +124,11 @@ export default class LokiTableMetadataStore implements ITableMetadataStore {
   public async createTable(context: Context, tableModel: Table): Promise<void> {
     // Check for table entry in the table registry collection
     const coll = this.db.getCollection(this.TABLES_COLLECTION);
+    // Azure Storage Service is case insensitive
+    const tableLower = tableModel.table.toLocaleLowerCase();
```
Comment (XiaoningLiu) [inline src/table/persistence/LokiTableMetadataStore.ts:128]: Somewhere you are using `toLowerCase()` and here use `toLocaleLowerCase()`. Is the difference by design?

File: src/table/handlers/TableHandler.ts [hunk 2]
```diff
@@ -53,7 +53,9 @@ export default class TableHandler extends BaseHandler implements ITableHandler {
     const tableContext = new TableStorageContext(context);
     const accept = this.getAndCheckPayloadFormat(tableContext);
     const account = this.getAndCheckAccountName(tableContext);
-    const table = tableProperties.tableName; // Table name is in request body instead of URL
+    // Table name is in request body instead of URL
+    // we must also force casing as service is case insensitive
+    const table = tableProperties.tableName?.toLowerCase();
```
Comment (XiaoningLiu) [inline src/table/handlers/TableHandler.ts:58]: If toLowers happen in metadataStore, seems we don't need handler layer do another toLower

File: src/table/persistence/LokiTableMetadataStore.ts (hunk 1 above)
Comment (edwin-huber) [reply src/table/persistence/LokiTableMetadataStore.ts:128]: No, this was an oversight, changed to toLowerCase()

File: src/table/handlers/TableHandler.ts (hunk 2 above)
Comment (edwin-huber) [reply src/table/handlers/TableHandler.ts:58]: Moved lower casing on create into MetaDatastore

File: src/table/persistence/LokiTableMetadataStore.ts [hunk 3]
```diff
@@ -160,17 +162,22 @@ export default class LokiTableMetadataStore implements ITableMetadataStore {
   ): Promise<void> {
     // remove table reference from collection registry
     const coll = this.db.getCollection(this.TABLES_COLLECTION);
+    // Azure Storage Service is case insensitive
+    const tableLower = table.toLocaleLowerCase();
     const doc = coll.findOne({
```
[the remark this answers is not in the document]
Comment (edwin-huber) [reply src/table/persistence/LokiTableMetadataStore.ts:168]: Updated to use a regex query to get the table collection, as this can be made case insensitive.
Added additional test to validate logic for delete being case insensitive.

**Comment by edwin-huber** [comment]
I shall change this PR to preserve casing on Tables as per Service behavior.

**Comment by XiaoningLiu** [comment]
> I shall change this PR to preserve casing on Tables as per Service behavior.

Service preserve the Table name casing, and comparison without case, for example:
- Create table "MyTable"
- List Tables should return "MyTable"
- Query/Create/Delete/Update/Merge Entities under table "MyTable" and "mytable" both should work

**Comment by edwin-huber** [comment]
Made changes and added tests to confirm preservation of case on table names.

**Review by XiaoningLiu — APPROVED** [review]
